sudo: required
language: ruby
rvm: 2.2
services:
    - docker
before_install:
    - docker pull $PGDOCKERIMAGE
    - docker run --name postgres -d $PGDOCKERIMAGE
    - docker ps -a
env:
    - PGDOCKERIMAGE=postgres:9.1
    - PGDOCKERIMAGE=postgres:9.2
    - PGDOCKERIMAGE=postgres:9.3
