#!/usr/bin/env ruby

# disable Slop warning with Ruby 2.7
$VERBOSE = nil

trap("SIGINT") { abort }

require "pgsync"

begin
  PgSync::Client.new(ARGV).perform
rescue PgSync::Error => e
  abort PgSync::Client.colorize(e.message, 31) # red
end
